name: Notify Slack on PR Events

on:
  pull_request:
    types: [opened, closed]

jobs:
  slack-notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Define Slack Message
        id: slack
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_NUM=${{ github.event.pull_request.number }}
          PR_URL="${{ github.event.pull_request.html_url }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          MERGED_BY="${{ github.event.pull_request.merged_by.login }}"
          ACTION="${{ github.event.action }}"
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"

          # Only proceed if base branch is dev
          if [[ "$BASE_BRANCH" != "dev" ]]; then
            echo "PR base branch is not dev. Skipping notification."
            echo "send_slack=no" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Match title to valid format (type(taskId): desc)
          if [[ "$PR_TITLE" =~ ^(feature|bug|fix|style)\(\d+\): ]]; then
            if [[ "$ACTION" == "opened" ]]; then
              TEXT="🛠️ *$AUTHOR* created a PR to \`dev\`: <${PR_URL}|#${PR_NUM}> - $PR_TITLE"
            elif [[ "$ACTION" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
              TEXT="✅ PR <${PR_URL}|#${PR_NUM}> - *${PR_TITLE}* created by *${AUTHOR}* has been merged to \`dev\` by *${MERGED_BY}*."
            else
              echo "No valid action for Slack notification."
              echo "send_slack=no" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "send_slack=yes" >> $GITHUB_OUTPUT
            echo "payload={\"text\": \"$TEXT\"}" >> $GITHUB_OUTPUT
          else
            echo "PR title does not match format. Skipping."
            echo "send_slack=no" >> $GITHUB_OUTPUT
            exit 0

      - name: Send Slack Notification
        if: steps.slack.outputs.send_slack == 'yes'
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '${{ steps.slack.outputs.payload }}' $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
